'use client'

import { useRef, useState, useEffect, useCallback } from 'react'
import { motion, useInView } from 'framer-motion'

// Audio files still stream directly from R2 (audio elements don't enforce CORS).
// The episodes manifest is served same-origin from public/episodes.json to avoid CORS.
const LEADER_BASE_URL = 'https://pub-dbab1e0013ed4466bdcf71d438319ead.r2.dev'

// GitHub Pages serves the app under /korean-portfolio/; Vercel serves it at root.
// Detect at runtime so we always fetch episodes.json from the same origin.
const getEpisodesPath = () => {
  if (typeof window === 'undefined') return '/episodes.json'
  return window.location.pathname.startsWith('/korean-portfolio')
    ? '/korean-portfolio/episodes.json'
    : '/episodes.json'
}

type PodcastLang = 'en' | 'ko' | 'es' | 'ja' | 'zh' | 'fr'

const PODCAST_LANGS: { code: PodcastLang; flag: string; label: string }[] = [
  { code: 'en', flag: '🇺🇸', label: 'EN' },
  { code: 'ko', flag: '🇰🇷', label: 'KO' },
  { code: 'es', flag: '🇪🇸', label: 'ES' },
  { code: 'ja', flag: '🇯🇵', label: 'JA' },
  { code: 'zh', flag: '🇨🇳', label: 'ZH' },
  { code: 'fr', flag: '🇫🇷', label: 'FR' },
]

interface Episode {
  title: string
  description: string
  url: string
  pub_date: string
  file_size: number
  versions?: Record<string, string>
}

interface Props { lang: 'ko' | 'en' }

function formatDate(dateStr: string, lang: 'ko' | 'en') {
  const d = new Date(dateStr)
  if (lang === 'ko') {
    return d.toLocaleDateString('ko-KR', { year: 'numeric', month: 'long', day: 'numeric' })
  }
  return d.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' })
}

function formatTime(seconds: number) {
  const m = Math.floor(seconds / 60)
  const s = Math.floor(seconds % 60)
  return `${m}:${s.toString().padStart(2, '0')}`
}

export default function LeaderPodcast({ lang }: Props) {
  const ref = useRef<HTMLElement>(null)
  const audioRef = useRef<HTMLAudioElement>(null)
  const inView = useInView(ref, { once: true, margin: '-80px' })

  const [episodes, setEpisodes] = useState<Episode[]>([])
  const [status, setStatus] = useState<'loading' | 'ok' | 'error'>('loading')
  const [activeIdx, setActiveIdx] = useState(0)
  const [playing, setPlaying] = useState(false)
  const [currentTime, setCurrentTime] = useState(0)
  const [duration, setDuration] = useState(0)
  const [podcastLang, setPodcastLang] = useState<PodcastLang>('en')

  useEffect(() => {
    fetch(getEpisodesPath())
      .then(r => { if (!r.ok) throw new Error(); return r.json() })
      .then((data: Episode[]) => { setEpisodes(data); setStatus('ok') })
      .catch(() => setStatus('error'))
  }, [])

  const current = episodes[activeIdx]
  const headlines = current?.description.split(' | ').filter(Boolean) ?? []
  const progress = duration ? (currentTime / duration) * 100 : 0
  const audioUrl = current?.versions?.[podcastLang] ?? current?.url ?? ''

  const togglePlay = useCallback(() => {
    const audio = audioRef.current
    if (!audio) return
    if (playing) {
      audio.pause()
      setPlaying(false)
    } else {
      audio.play().then(() => setPlaying(true)).catch(() => setPlaying(false))
    }
  }, [playing])

  const handleSeek = (e: React.ChangeEvent<HTMLInputElement>) => {
    const t = Number(e.target.value)
    if (audioRef.current) { audioRef.current.currentTime = t; setCurrentTime(t) }
  }

  const switchEpisode = (idx: number) => {
    if (idx === activeIdx) return
    setActiveIdx(idx)
    setPlaying(false)
    setCurrentTime(0)
    setDuration(0)
  }

  const switchPodcastLang = (code: PodcastLang) => {
    if (code === podcastLang) return
    setPodcastLang(code)
    setPlaying(false)
    setCurrentTime(0)
    setDuration(0)
  }

  return (
    <section id="leader-podcast" ref={ref} className="w-full py-24">
      <div className="section-inner">

        {/* Section header */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.7 }}
          className="text-center mb-12"
        >
          <span className="font-mono text-[#39ff14] text-sm tracking-widest uppercase">
            {lang === 'ko' ? '매일 아침 AI 기술 뉴스' : 'Daily AI Tech News'}
          </span>
          <h2 className="text-4xl sm:text-5xl font-bold mt-2">
            LEADER Podcast
          </h2>
          <div className="mt-3 h-0.5 w-20 bg-gradient-to-r from-[#39ff14] to-[#00f5ff] mx-auto" />
          <p className="mt-4 text-gray-400 text-sm max-w-xl mx-auto leading-relaxed">
            {lang === 'ko'
              ? 'JUNO(학생)와 ALEX(전문가)가 매일 아침 6시 TLDR Tech 뉴스 3건을 2분 대화로 전달합니다. Groq Llama 3.3 70B + edge-tts로 완전 자동 생성 후 GitHub Actions → Cloudflare R2로 배포.'
              : 'JUNO & ALEX deliver 3 daily TLDR Tech headlines as a 2-min dialogue every morning at 6 AM KST — auto-generated by Groq Llama 3.3 70B + edge-tts, deployed via GitHub Actions to Cloudflare R2.'}
          </p>
        </motion.div>

        {/* Loading */}
        {status === 'loading' && (
          <div className="flex items-center justify-center gap-3 py-16 text-gray-500">
            <div className="w-5 h-5 border-2 border-[#39ff14]/30 border-t-[#39ff14] rounded-full animate-spin" />
            <span className="font-mono text-sm">
              {lang === 'ko' ? '에피소드 불러오는 중...' : 'Loading episodes...'}
            </span>
          </div>
        )}

        {/* Error / not connected */}
        {status === 'error' && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="max-w-lg mx-auto rounded-2xl p-8 text-center"
            style={{ background: 'rgba(57,255,20,0.04)', border: '1px solid rgba(57,255,20,0.15)' }}
          >
            <div className="text-5xl mb-4">🎙️</div>
            <p className="text-gray-400 text-sm mb-5 leading-relaxed">
              {lang === 'ko'
                ? 'R2 버킷이 아직 연결되지 않았습니다. 아래 GitHub에서 파이프라인 코드를 확인하세요.'
                : 'Podcast pipeline not yet live. Check out the source on GitHub below.'}
            </p>
            <a
              href="https://github.com/markyang0613/leader_podcast"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg text-sm font-mono text-[#39ff14] transition-all hover:bg-[#39ff14]/10"
              style={{ border: '1px solid rgba(57,255,20,0.3)' }}
            >
              GitHub ↗
            </a>
          </motion.div>
        )}

        {/* Player */}
        {status === 'ok' && current && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="grid grid-cols-1 lg:grid-cols-3 gap-5"
          >
            {/* ── Main player card ── */}
            <div
              className="lg:col-span-2 rounded-2xl p-6 flex flex-col gap-5 relative overflow-hidden"
              style={{
                background: 'rgba(255,255,255,0.03)',
                border: '1px solid rgba(57,255,20,0.25)',
                backdropFilter: 'blur(12px)',
              }}
            >
              {/* Top gradient bar */}
              <div className="absolute top-0 left-0 right-0 h-[3px] bg-gradient-to-r from-[#39ff14] to-[#00f5ff]" />

              {/* Meta row */}
              <div className="flex items-center gap-2 flex-wrap">
                <span className="px-2.5 py-0.5 rounded-md text-xs font-mono font-bold text-black bg-[#39ff14]">
                  {lang === 'ko' ? '최신' : 'LATEST'}
                </span>
                <span className="text-xs text-gray-500 font-mono">
                  {formatDate(current.pub_date, lang)}
                </span>
              </div>

              {/* Episode title */}
              <h3 className="font-bold text-lg leading-snug">{current.title}</h3>

              {/* News headlines */}
              {headlines.length > 0 && (
                <ul className="flex flex-col gap-2">
                  {headlines.map((h, i) => (
                    <li key={i} className="flex items-start gap-2 text-gray-400 text-sm">
                      <span className="text-[#39ff14] flex-shrink-0 mt-0.5">▸</span>
                      {h}
                    </li>
                  ))}
                </ul>
              )}

              {/* Hidden audio element */}
              <audio
                ref={audioRef}
                src={audioUrl}
                preload="none"
                onTimeUpdate={() => audioRef.current && setCurrentTime(audioRef.current.currentTime)}
                onLoadedMetadata={() => audioRef.current && setDuration(audioRef.current.duration)}
                onEnded={() => setPlaying(false)}
              />

              {/* Language selector */}
              <div className="flex flex-col gap-2">
                <p className="text-xs font-mono text-gray-500 uppercase tracking-widest">
                  {lang === 'ko' ? '언어 선택' : 'Language'}
                </p>
                <div className="flex flex-wrap gap-2">
                  {PODCAST_LANGS.map(({ code, flag, label }) => {
                    const available = !!(current?.versions?.[code] || code === 'en')
                    const active = podcastLang === code
                    return (
                      <button
                        key={code}
                        onClick={() => switchPodcastLang(code)}
                        disabled={!available}
                        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-mono transition-all duration-200 disabled:opacity-30 disabled:cursor-not-allowed"
                        style={{
                          background: active ? 'rgba(57,255,20,0.12)' : 'rgba(255,255,255,0.04)',
                          border: active ? '1px solid rgba(57,255,20,0.5)' : '1px solid rgba(255,255,255,0.1)',
                          color: active ? '#39ff14' : '#9ca3af',
                        }}
                      >
                        <span>{flag}</span>
                        <span>{label}</span>
                      </button>
                    )
                  })}
                </div>
              </div>

              {/* Controls */}
              <div className="flex flex-col gap-3 mt-auto">
                {/* Seek bar */}
                <div className="flex items-center gap-2 text-xs font-mono text-gray-500">
                  <span className="w-8 text-right">{formatTime(currentTime)}</span>
                  <div className="relative flex-1 h-1.5 rounded-full overflow-hidden" style={{ background: 'rgba(255,255,255,0.08)' }}>
                    <div
                      className="absolute left-0 top-0 h-full rounded-full transition-all"
                      style={{ width: `${progress}%`, background: 'linear-gradient(90deg, #39ff14, #00f5ff)' }}
                    />
                    <input
                      type="range"
                      min={0}
                      max={duration || 120}
                      value={currentTime}
                      onChange={handleSeek}
                      className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                    />
                  </div>
                  <span className="w-8">{formatTime(duration || 0)}</span>
                </div>

                {/* Play / Pause button */}
                <button
                  onClick={togglePlay}
                  className="flex items-center justify-center gap-3 w-full py-4 rounded-xl font-bold text-base transition-all duration-200 hover:opacity-90 active:scale-95"
                  style={{
                    background: playing
                      ? 'linear-gradient(135deg, rgba(57,255,20,0.12), rgba(0,245,255,0.08))'
                      : 'linear-gradient(135deg, rgba(57,255,20,0.22), rgba(0,245,255,0.12))',
                    border: '1px solid rgba(57,255,20,0.45)',
                    color: '#39ff14',
                  }}
                >
                  {playing ? (
                    <>
                      <span className="text-xl leading-none">⏸</span>
                      <span>{lang === 'ko' ? '일시정지' : 'Pause'}</span>
                    </>
                  ) : (
                    <>
                      <span className="text-xl leading-none">▶</span>
                      <span>{lang === 'ko' ? '지금 듣기' : 'Play Now'}</span>
                    </>
                  )}
                </button>
              </div>
            </div>

            {/* ── Episode list sidebar ── */}
            <div className="flex flex-col gap-3">
              <p className="text-xs font-mono text-gray-500 uppercase tracking-widest px-1">
                {lang === 'ko' ? '에피소드 목록' : 'Episodes'}
              </p>

              {episodes.slice(0, 5).map((ep, i) => (
                <button
                  key={i}
                  onClick={() => switchEpisode(i)}
                  className="rounded-xl p-4 text-left transition-all duration-200"
                  style={{
                    background: i === activeIdx ? 'rgba(57,255,20,0.06)' : 'rgba(255,255,255,0.02)',
                    border: i === activeIdx
                      ? '1px solid rgba(57,255,20,0.4)'
                      : '1px solid rgba(255,255,255,0.06)',
                    backdropFilter: 'blur(8px)',
                  }}
                >
                  <div className="flex items-center gap-2 mb-1.5">
                    <span
                      className="text-xs font-mono"
                      style={{ color: i === activeIdx ? '#39ff14' : '#4b5563' }}
                    >
                      {i === activeIdx && playing ? '▶' : String(i + 1).padStart(2, '0')}
                    </span>
                    <span className="text-xs text-gray-500 font-mono">
                      {new Date(ep.pub_date).toLocaleDateString(
                        lang === 'ko' ? 'ko-KR' : 'en-US',
                        { month: 'short', day: 'numeric' }
                      )}
                    </span>
                  </div>
                  <p className="text-sm text-gray-300 leading-snug line-clamp-2">{ep.title}</p>
                </button>
              ))}

              {/* RSS subscribe */}
              <a
                href={`${LEADER_BASE_URL}/feed.xml`}
                target="_blank"
                rel="noopener noreferrer"
                className="mt-1 flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl text-xs font-mono transition-all hover:bg-[#00f5ff]/5"
                style={{ border: '1px solid rgba(0,245,255,0.2)', color: '#00f5ff' }}
              >
                RSS {lang === 'ko' ? '구독하기' : 'Subscribe'} ↗
              </a>
            </div>
          </motion.div>
        )}
      </div>
    </section>
  )
}
